---------------------------------------------------------------------------------------------------
-- Issue: https://github.com/smartdevicelink/sdl_core/issues/3931
---------------------------------------------------------------------------------------------------
-- Description:
-- Test script to check that UI.SetGlobalProperties is generated by SDL
-- for AddCommand request sent after ResetGlobalProperties
--
-- Preconditions:
-- 1) SDL, HMI, Mobile session are started
-- 2) Mobile app is registered
-- 3) Application is activated
-- 4) App sends AddCommand with menuName and vrCommands
-- SDL does:
--  a. Send UI.AddCommand to the HMI with menuParams
--  b. Send VR.AddCommand to the HMI with vrCommands
--  c. Send UI.SetGlobalProperties to the HMI with vrHelp and vrHelpTitle
-- 5) App sends SetGlobalProperties with vrHelp and verHelpTitle
-- SDL does:
--  a. Send UI.SetGlobalProperties to the HMI with vrHelp and vrHelpTitle
-- 6) App sends ResetGlobalProperties with properties: {"VRHELPTITLE", "VRHELPITEMS"}
-- SDL does:
--  a. Send UI.SetGlobalProperties to the HMI with vrHelp and vrHelpTitle
--
-- Steps:
-- 1) App sends AddCommand with menuName and vrCommands
-- SDL does:
--  a. Send UI.AddCommand to the HMI with menuParams
--  b. Send VR.AddCommand to the HMI with vrCommands
--  c. Send UI.SetGlobalProperties to the HMI with vrHelp and vrHelpTitle
---------------------------------------------------------------------------------------------------
--[[ Required Shared libraries ]]
local runner = require('user_modules/script_runner')
local common = require('test_scripts/Defects/8_2/3931/common')

--[[ Test Configuration ]]
runner.testSettings.isSelfIncluded = false

--[[ Local Variables ]]

local addCommandParams = {
  [1] = {cmdID = 1, menuParams = {menuName = "Menu name"}, vrCommands = {"vr 1", "vr 2"} },
  [2] = {cmdID = 10, menuParams = {menuName = "Second Menu name"}, vrCommands = {"VR Command 1", "VR Command 2", "VR Command 3"}}
}

local setGlobalPropertiesParams = {
  vrHelpTitle = "Help title",
  vrHelp = { 
    {text = "Help item 1", position = 1},
    {text = "Help item 2", position = 2}
  }
}

local resetParams = { 
  properties = {"VRHELPTITLE", "VRHELPITEMS"}
}

--[[ Scenario ]]
runner.Title("Preconditions")
runner.Step("Clean environment", common.preconditions)
runner.Step("Start SDL, HMI, connect Mobile, start Session", common.start)
runner.Step("Register App", common.registerApp)
runner.Step("Activate App", common.activateApp)
runner.Step("First AddCommand", common.AddCommand, { addCommandParams[1] })
runner.Step("SetGlobalProperties", common.SetGlobalProperties, { setGlobalPropertiesParams })
runner.Step("ResetGlobalProperties", common.ResetGlobalProperties, { resetParams })

runner.Title("Test")
runner.Step("Second AddCommand", common.AddCommand, { addCommandParams[2] })

runner.Title("Postconditions")
runner.Step("Stop SDL", common.postconditions)
