---------------------------------------------------------------------------------------------------
-- Issue: https://github.com/smartdevicelink/sdl_core/issues/3931
---------------------------------------------------------------------------------------------------
-- Description:
-- Test script to check that TTS.SetGlobalProperties requests is generated by SDL
-- for AddCommand request sent after ResetGlobalProperties
--
-- Preconditions:
-- 1) SDL, HMI, Mobile session are started
-- 2) Mobile app is registered
-- 3) Application is activated
-- 4) App sends AddCommand with menuName
-- SDL does:
--  a. Send UI.AddCommand to the HMI with menuParams
--  b. Send TTS.SetGlobalProperties to the HMI with helpPrompt
-- 5) App sends SetGlobalProperties with helpPrompt
-- SDL does:
--  a. Send TTS.SetGlobalProperties to the HMI with helpPrompt
-- 6) App sends ResetGlobalProperties with properties: {"HELPPROMPT"}
-- SDL does:
--  a. Send TTS.SetGlobalProperties to the HMI with helpPrompt
--
-- Steps:
-- 1) App sends AddCommand with menuName
-- SDL does:
--  a. Send UI.AddCommand to the HMI with menuParams
--  b. Send TTS.SetGlobalProperties to the HMI with helpPrompt
---------------------------------------------------------------------------------------------------
--[[ Required Shared libraries ]]
local runner = require('user_modules/script_runner')
local common = require('test_scripts/Defects/8_2/3931/common')

--[[ Test Configuration ]]
runner.testSettings.isSelfIncluded = false

--[[ Local Variables ]]

local addCommandParams = {
  [1] = {cmdID = 1, menuParams = {menuName = "Menu name"}},
  [2] = {cmdID = 10, menuParams = {menuName = "Second Menu name"}}
}

local setGlobalPropertiesParams = {
  helpPrompt = { {text = "Prompt", type = "TEXT"} }
}

local resetParams = { 
  properties = {"HELPPROMPT"}
}

--[[ Scenario ]]
runner.Title("Preconditions")
runner.Step("Clean environment", common.preconditions)
runner.Step("Start SDL, HMI, connect Mobile, start Session", common.start)
runner.Step("Register App", common.registerApp)
runner.Step("Activate App", common.activateApp)
runner.Step("First AddCommand", common.AddCommand, { addCommandParams[1] })
runner.Step("SetGlobalProperties", common.SetGlobalProperties, { setGlobalPropertiesParams })
runner.Step("ResetGlobalProperties", common.ResetGlobalProperties, { resetParams })

runner.Title("Test")
runner.Step("Second AddCommand", common.AddCommand, { addCommandParams[2] })

runner.Title("Postconditions")
runner.Step("Stop SDL", common.postconditions)
